### ISSUE TITLE
Allow multiple manipulation operations in one link

### ISSUE THREAD

**Issue by jacobwindsor** [jacobwindsor/kaavio-showdown#1]
Currently, you can only do one manipulation per link. It would be useful for some users to do multiples at once. For example, zooming on a group of nodes and highlighting one of them at the same time.

The syntax for this could be something like

```
[some text]!!zoomOn 'node1,node2,node3' | toggleHighlight 'node2' 'red!!
```
The `|` pipe denotes the seperation of manipulations to perform.

What would the RegEx for this be?

**Comment by ariutta** [comment]
I took a look at several formats to see how they might be related to this issue, as you can see in Reference Examples below. Just brainstorming, here are a few more ideas to play around with:

* Just use a WYSIWYG visual editor (no markdown)
* Extend Commonmark w/ S-expressions for key value pairs (key: string, value: entries before next string)
**  Option using `!!` as delimiter ([rough code](https://gist.github.com/ariutta/53544531d60b632c417c90eee41aea37)):
`[some text]!!(zoomOn (node1 node2 node3) toggleHighlight (node2 red) (node3 yellow))!!`
** Option using `KS` as namespace ([rough code](https://gist.github.com/ariutta/67f36fca118ce99ae5b87eb52825dcf0)):
`KS[some text](zoomOn (node1 node2 node3) toggleHighlight (node2 red) (node3 yellow))`
* Extend Commonmark with a variation on [SLIM attribute merging](http://www.rubydoc.info/gems/slim/frames#Attribute_merging)
** `KS[some text](zoomOn="node1, node2, node3" toggleHighlight="node2 red, node3 yellow")`
* Extend Commonmark with a CSS-like syntax
** `KS[some text](zoomOn {nodes: node1, node2, node3} toggleHighlight {node2: red; node3: yellow})`
* Extend Commonmark with querystring-like syntax
** `KS[some text](zoomOn=node1,node2,node3&toggleHighlight=node2,red;node3,yellow)`
* Extend Commonmark with JS-like syntax
** `KS[some text](zoomOn(node1, node2, node3) toggleHighlight({node2: red}, {node3: yellow}))`
* Extend Commonmark with JSON
** `KS[some text]([{"zoomOn": ["node1", "node2", "node3"]}, {"toggleHighlight": [{"node2": "red"}, {"node3": "yellow"}]}])`


# Reference Examples

## Commonmark / GF Markdown
* Link `[demo](http://github.com)` [demo](http://github.com)
* Link w/ title (hover to view) `[demo](http://spec.commonmark.org/0.26/#example-456 "see spec")` [demo](http://spec.commonmark.org/0.26/#example-456 "see spec")
* Image `![img description](/logo.png)`
* Image w/ alt text `![img description](/logo.png "some alt text")`

## Wikitext
* large red text `{{color|red|{{{resize|150%|text}}}}`

## Lean versions of HTML

Check your browser console to see the output from the following formats.

### [SLIM](http://www.rubydoc.info/gems/slim/frames#Attributes) ([live](https://codepen.io/ariutta/pen/bWbOzG))
`p onClick="c(zoomOn('node1,node2,node3'), toggleHighlight('node2', 'red'))" clickme`

### HAML ([live](https://codepen.io/ariutta/pen/aWoXvG))
`%p(onClick="c(zoomOn('node1,node2,node3'), toggleHighlight('node2', 'red'))") clickme`

### Pug ([live](https://codepen.io/ariutta/pen/xdKMVz))
`p(onclick='c(zoomOn("abc,def,hij"), toggleHighlight("abc", "red"))') clickme`

**Comment by ariutta** [comment]
One item to consider regarding the pipe: on the Linux command line, that indicates that the result of the previous operation is passed to the next. If that's not true in this case, could it be confusing? If so, we could consider using another symbol like `&`.

**Comment by jacobwindsor** [comment]
Thanks for taking a look :smile: 

# WYSIWYG
Personally, I prefer this option over any Markdown in terms of UI. I think the manipulation operations are just too lengthy for Markdown. However, the issue is development time...

The markdown option is so easy to develop and unit test. It's also so easy to integrate into WPs. You can keep the backend storage of descriptions the same and just use jQuery to parse the Markdown.

# Extending Commonmark
Any extensions to Commonmark should be easy to understand and easy to remember. The latter is harder since some manipulation operations need many parameters and the order of them is crucial. For example,

```markdown
[some text]!!zoomOn 'node1' 'others'!! // easy to remember

[some text]!!toggleHighlight 'node1' 'red' 'others'!! // harder to remember because of the extra parameter.
```
 ## Your ideas 
- I like the namespace. I'd suggest just `K` though.
- Querystring and JSON are hard to understand. Maybe even overwhelming for non-devs. However, I do like that each parameter is named so order doesn't matter.
- SLIM attribute merging is visually the most pleasing and approachable I think. However, it does have the same issue of requiring a specific parameter ordering.
- CSS-like syntax is less visually pleasing because of the `{}`. But... the attributes can be named. 
- JS Syntax works well but only if there is one parameter per call. There are a lot of brackets though and it's easy to forget closing them!
- I don't think lean HTML is an option since it's too difficult to understand for non-devs.


## Mistake(?) in CSS and SLIM examples
  - Small thing: in your example the specification of toggleHighlight is wrong. Every node in the list is highlighted one color. 
  - To achieve the behaviour in your example you'd had to do:
```toggleHighlight {nodes: node2; color: red} toggleHighlight {nodes: node3; color: yellow}```
  - I've opened [this issue](https://github.com/wikipathways/pvjs/issues/392) to discuss this further.

# Just one parameter
Thinking about everything, the issues really come when there are multiple required parameters. In all of the manipulation functions, there is a resets object as a parameter. For toggleHighlight this is:

```
{others: boolean, hidden: boolean, panZoom: boolean}
```

I integrated this since it's really needed when you can't do multiple operations in Markdown. However, with multiples enabled you may as well just do (in JS-like syntax):

```
K[some text](zoomOn(node1, node2, node3) toggleHighlight({node2: red}, {node3: yellow}) resetPanZoom(node1) resetHidden(node2) resetHighlighted(node1,node2))
```

Where the parameters to the resets are entities that are excluded from resetting.

Relating to [this issue](https://github.com/wikipathways/pvjs/issues/392), if we only allow one parameter per manipulation method then we must use the alternative syntax.

**Comment by ariutta** [comment]
Yeah, I was wondering about that toggleHighlight syntax.

I'll have to think about this a bit. Do Egon or the other researcher you're working with have any preferences?

BTW, I ran across another format called [edn](https://github.com/edn-format/edn). Here's an [online playground](http://shaunxcode.github.io/jsedn/), in case you didn't get enough examples above. 😆

**Comment by jacobwindsor** [comment]
[Related](https://github.com/jacobwindsor/MetabMaster/issues/18). Using a WYSIWYG -> markdown editor could solve these issues and also give the possibility for easy state tracking.

**Comment by jacobwindsor** [comment]
Done in #4
